### ISSUE TITLE
[20] Documentation

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#2]
**Tasks, due dates, and assignments are in Asana**

https://app.asana.com/0/12738245044252/388775086235196

Create a white paper in pdf format that documents our process building and improving the College Women website. The white paper can be easily distributed by both BMC and IM through various channels, can be used for future writing and speaking opportunities, and can answer the call of the grant to share the process. The initial outline of the paper will also be used as the grant progress report due at the end of May. 

The white paper will include the following topics:
- [x] Process summary - wireframes, designs, Drupal, modules
- [x] Working with Feeds OAI-PMH and having to adapt it
- [x] Using REPOX to make data consistent
- [x] Ongoing improvements, like what is in the wish list

**Comment by amberreeves** [comment]
This work has been approved.

**Comment by amberreeves** [comment]
First draft has been delivered. Any new tasks attached to this will be tracked separately.

**Comment by amberreeves** [comment]
From Evan: the documentation looks good to us. The only things left to be worked on are mostly our internal notes and we'll be addressing those.
